PrivateRoute1:   # Public route table has direct routing to IGW:
  Type: AWS::EC2::Route
  Properties:
    RouteTableId: 
      Ref: PrivateRouteTable
    DestinationCidrBlock: 0.0.0.0/0
    # Route traffic through the NAT Gateway:
    NatGatewayId:
      Ref: NATGateway