AccessPointResource:
  Type: 'AWS::EFS::AccessPoint'
  Properties:
    FileSystemId: 
      Ref: FileSystemResource
    PosixUser:
      Uid: "1000"
      Gid: "1000"
    RootDirectory:
      CreationInfo:
        OwnerGid: "1000"
        OwnerUid: "1000"
        Permissions: "0777"
      Path: "/myefs"